
"use client"
import './globals.css'
import React,{useState} from "react"
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from "./Components/Navbar"
import { Provider } from 'react-redux'
import Footer from "./Components/Footer"
import { store } from '@/redux/store'
import CartProduct from './Components/CartProduct'
import Cart from './Components/Cart'
// import Cart from "./Components/Cart.tsx"
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Cosmetic Website',
  description: 'Generated by create next app',
  // utf8: true,
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [showcart,setshowcart]=useState(false)
  
  return (
    <html lang="en">
      <body className={inter.className}>
    
      <Provider store={store} >
        <Navbar setshowcart={setshowcart}/>
        {showcart&&<Cart setshowcart={setshowcart}/>}
        {children}
        <Footer />

        </Provider>
        </body>
    </html>
  )
}
