import React from "react";
import product1 from "../../assets/product_1.png";
import product2 from "../../assets/product_2.jpg";
import product3 from "../../assets/product_3.jpeg";
import product4 from "../../assets/product_4.jpeg";
import product5 from "../../assets/product_5.jpg";
import product6 from "../../assets/product_6.png";
import product7 from "../../assets/product_7.png";
import product8 from "../../assets/product_8.jpg";
import product9 from "../../assets/product_9.png";
import product10 from "../../assets/product_10.png";
import product11 from "../../assets/product_11.jpeg";
import product12 from "../../assets/product_2.jpg";
import product14 from "../../assets/12.jpg";
import product15 from "../../assets/13.png";
import product16 from "../../assets/14.png";
import product17 from "../../assets/15.png";
export default [
    {
      id: 0,
      img: product1,
      name: "Luxury Red Lipstick",
      price: 25.99,
      category: ["lipstick"],
      sale: false,
    },
    {
      id: 1,
      img: product2,
      name: "Silky Smooth Foundation",
      price: 32.50,
      category: ["makeup"],
      sale: true,
    },
    {
      id: 2,
      img: product4,
      name: "Radiant Rose Blush",
      price: 18.75,
      category: ["makeup"],
      sale: false,
    },
    {
      id: 3,
      img: product5,
      name: "Moisturizing Day Cream",
      price: 27.99,
      category: ["skin care"],
      sale: true,
    },
    {
      id: 4,
      img: product6,
      name: "Anti-Aging Serum",
      price: 36.95,
      category: ["skin care"],
      sale: false,
    },
    {
      id: 5,
      img: product2,
      name: "Natural Mascara",
      price: 14.99,
      category: ["skin care"],
      sale: false,
    },
    {
      id: 6,
      img: product7,
      name: "Revitalizing Vitamin C Serum",
      price: 34.99,
      category: ["skin care"],
      sale: false,
    },
    {
      id: 7,
      img: product8,
      name: "Hydrating Rosewater Mist",
      price: 15.99,
      category: ["skin care"],
      sale: false,
    },
    {
      id: 8,
      img: product9,
      name: "Elegant Makeup Brush Set",
      price: 29.99,
      category: ["makeup"],
      sale: false,
    },
    {
      id: 9,
      img: product10,
      name: "Scented Bath Bombs",
      price: 12.99,
      category: ["skin care"],
      sale: false,
    },
    {
      id: 10,
      img: product11,
      name: "Luxurious Silk Eye Mask",
      price: 9.99,
      category: ["nail & wax"],
      sale: false,
    },
    {
      id: 11,
      img: product12,
      name: "Nourishing Hair Oil",
      price: 19.50,
      category: ["skin care"],
      sale: false,
    },
    {
      id: 12,
      img: product3,
      name: "Exfoliating Face Scrub",
      price: 16.75,
      category: ["skin care"],
      sale: false,
    },
    {
      id: 13,
      img: product14,
      name: "Luxury Perfume",
      price: 49.99,
      category: ["lipstick"],
      sale: true,
    },
    {
      id: 14,
      img: product15,
      name: "Volumizing Mascara",
      price: 15.99,
      category: ["makeup"],
      sale: false,
    },
    {
      id: 15,
      img: product16,
      name: "Organic Night Cream",
      price: 28.99,
      category: ["nail & wax"],
      sale: true,
    },
    {
      id: 16,
      img: product17,
      name: "Gentle Cleansing Foam",
      price: 12.49,
      category: ["skin care"],
      sale: false,
    },
    {
      id: 17,
      img: product12,
      name: "Fruity Lip Balm",
      price: 5.99,
      category: ["lipstick"],
      sale: false,
    },
    {
      id: 18,
      img: product15,
      name: "Luxury Hair Perfume",
      price: 22.99,
      category: ["nail & wax"],
      sale: false,
    },
    {
      id: 19,
      img: product2,
      name: "Soothing Aloe Vera Gel",
      price: 10.99,
      category: ["nail & wax"],
      sale: false,
    },
    {
      id: 20,
      img: product5,
      name: "Luminous Highlighter",
      price: 17.50,
      category: ["makeup"],
      sale: true,
    },
    {
      id: 21,
      img: product6,
      name: "Cucumber Cooling Mask",
      price: 8.99,
      category: ["skin care"],
      sale: false,
    },
    {
      id: 22,
      img: product7,
      name: "Matte Lipstick",
      price: 19.99,
      category: ["lipstick"],
      sale: false,
    },
    {
      id: 23,
      img: product8,
      name: "Rose Petal Toner",
      price: 11.49,
      category: ["skin care"],
      sale: true,
    },
    {
      id: 24,
      img: product9,
      name: "Glowing Body Oil",
      price: 24.99,
      category: ["skin care"],
      sale: false,
    },
    {
      id: 25,
      img: product10,
      name: "Shimmering Eyeshadow Palette",
      price: 22.50,
      category: ["makeup"],
      sale: false,
    },
    {
      id: 26,
      img: product16,
      name: "Luxury Hand Cream",
      price: 9.99,
      category: ["nail & wax"],
      sale: false,
    },
    {
      id: 27,
      img: product17,
      name: "Refreshing Face Mist",
      price: 7.99,
      category: ["skin care"],
      sale: false,
    },
    {
      id: 28,
      img: product14,
      name: "Natural Lip Gloss",
      price: 12.99,
      category: ["lipstick"],
      sale: false,
    },
    {
      id: 29,
      img: product9,
      name: "Pearlescent Nail Polish",
      price: 9.99,
      category: ["nail & wax"],
      sale: false,
    },
    {
      id: 30,
      img: product1,
      name: "Tinted Sunscreen",
      price: 20.99,
      category: ["skin care"],
      sale: true,
    },
    {
      id: 31,
      img: product2,
      name: "Glamorous False Eyelashes",
      price: 14.99,
      category: ["makeup"],
      sale: false,
    },
    {
      id: 32,
      img: product8,
      name: "Botanical Body Wash",
      price: 11.99,
      category: ["skin care"],
      sale: false,
    },
  ];
  

  
